### ISSUE TITLE
Support for netstandard2.0

### ISSUE THREAD

**Issue by Kesmy** [alexandrnikitin/Topshelf.Unity#17]
Since both Topshelf and Unity support net452 and netstandard2.0, should Topshelf.Unity also multi-target both?

**Comment by alexandrnikitin** [comment]
@Kesmy Yes, it would be great! Help appreciated!

**Comment by Kesmy** [comment]
Note for myself (or if I get hit by a bus...):

This will result in minimum-version upgrades to Topshelf 4.2.1 and Unity.Abstractions 4.1.0, to minimize the number of additional dependencies.

**Comment by kstrt** [comment]
Hey. Hope you don't mind me taking this one (it has been open a while 😄)

I've just opened PR [#19](https://github.com/alexandrnikitin/Topshelf.Unity/pull/19) that should support netstandard2.0 and net452.

**Comment by alexandrnikitin** [comment]
Closed by #19 
@kstrt  @Kesmy Thank you for your contribution! Appreciate it.
