### ISSUE TITLE
Error	CS8002: Referenced assembly 'Topshelf.Unity' does not have a strong name.

### ISSUE THREAD

**Issue by voroninp** [alexandrnikitin/Topshelf.Unity#3]
Our company's policy requires us to deploy only signed assemblies. Signed assemblies cannot reference not signed libraries.

**Comment by alexandrnikitin** [comment]
Hi Pavel,

I have strong opinion against signed assemblies. Based on my experience signed assemblies cause only problems while they don't bring any benefits. Feel free to contribute the build script for creating the signed assembly package. (I really like FAKE http://fsharp.github.io/FAKE/)
Another option is just to copy the sources into your project.
