### ISSUE TITLE
Topshelf.Unity is not compatible with latest Unity 5.0.1

### ISSUE THREAD

**Issue by fabricioferreira** [alexandrnikitin/Topshelf.Unity#4]
Unable to resolve dependencies. 'Unity 5.0.1' is not compatible with 'Topshelf.Unity 3.0.1 constraint: Unity (>= 4.0.0 && < 5.0.0)'.

Are there any plans to update?

According to the documentation ([here](https://github.com/unitycontainer/unity/tree/v5.x#v5x)), the version 5.x doesn't have compatibility issues, however they had to change namespaces and other stuff in order to make it work.

**Comment by alexandrnikitin** [comment]
@fabricioferreira Thank you for raising this. The idea was to limit the Unity's major version to 4.x.x and avoid possible breaking changes. To fix it one needs to test the library against Unity 5.x.x and relax [the constraint.](
https://github.com/alexandrnikitin/Topshelf.Unity/blob/master/src/Topshelf.Unity/Topshelf.Unity.nuspec#L16) Will you be able to find time for this?

**Comment by alexandrnikitin** [comment]
I just published the v3.1.0 with Unity 5.x.x support. Feel free to try. cc @istagir

**Comment by fabricioferreira** [comment]
Thanks @alexandrnikitin! I'm sorry for not replying before. I'm in between jobs now, so it is being crazier than usual. I hope I can contribute more in the future.
