### ISSUE TITLE
Unity.Abstractions Dependency

### ISSUE THREAD

**Issue by jcabot21** [alexandrnikitin/Topshelf.Unity#6]
At the moment of writing the package **Unity.Abstractions** is in version **3.1.2** this causes a conflict when attempting to update Unity in a project using the **Topshelf.Unity** package because it is bound to version between **2.0.0** and **3.0.0**.

**Comment by alexandrnikitin** [comment]
Fixed by #7 
Published [v3.1.1](https://www.nuget.org/packages/Topshelf.Unity/3.1.1)
